{
  "name": "CI",
  "on": {
    "pull_request": null
  },
  "jobs": {
    "run-tests": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin"
      },
      "steps": [
        {
          "name": "Install raylib...",
          "run": "sudo add-apt-repository ppa:texus/raylib && sudo apt-get update && sudo apt-get install -y libraylib5-dev",
          "shell": "bash"
        },
        {
          "name": "install libgl-dev",
          "run": "sudo apt-get install libgl-dev",
          "shell": "bash"
        },
        {
          "name": "checkout raygui",
          "uses": "actions/checkout@v4",
          "with": {
            "repository": "raysan5/raygui",
            "path": "raygui",
            "ref": "master"
          }
        },
        {
          "name": "compile raygui lib",
          "run": "cd raygui \n             mv src/raygui.h src/raygui.c \n             gcc -o raygui.so src/raygui.c -shared -fpic -DRAYGUI_IMPLEMENTATION -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 \n             sudo cp raygui.so /usr/lib/ \n             mv src/raygui.c src/raygui.h",
          "shell": "bash"
        },
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "gamebits",
            "cache": "false"
          }
        },
        {
          "name": "Run Tests",
          "uses": "40ants/run-tests@v2",
          "with": {
            "asdf-system": "gamebits",
            "coveralls-token": "${{ secrets.github_token }}"
          }
        }
      ]
    }
  }
}